remove bin/schedule

diff --git a/bin/gauge b/bin/gauge
--- a/bin/gauge
+++ b/bin/gauge
@@ -4,10 +4,12 @@ set -eE
 
 # Test a merge point on master
 #
-# usage: gauge PR COMMIT
+# usage: gauge [-o FILE]  PR COMMIT
+#
+#    -o FILE     output file for the data
 #
 # e.g.
-#        gauge 2874 a2dbd
+#        gauge -o /path/to/data.csv 2874 a2dbd
 
 
 if [ -z "$PROG_HOME" ] ; then
@@ -48,11 +50,35 @@ trap report ERR
 
 ## init
 
+# parse command line params
+while getopts "o:" opt; do
+ case $opt in
+    o)
+      FILE=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+
+shift $((OPTIND-1))
+
+if [[ -z $FILE ]]; then
+  FILE="$PROG_HOME/history.csv"
+  echo "output file defaults to history.csv"
+fi
+
 cd $PROG_HOME
 PR=$1
 COMMIT=$2
 LOG="$PROG_HOME/logs/pr-$PR-$COMMIT.out"
-FILE="$PROG_HOME/history.csv"
 
 source "$PROG_HOME/bin/config"
 source "$PROG_HOME/bin/common"
diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -2,11 +2,12 @@
 
 set -eE
 
-# usage: run [-f PR] [-t PR] [-s STEP]
+# usage: run [-f PR] [-t PR] [-s STEP] [-o FILE]
 #
 # -f PR             from pull request (excluded)
 # -t PR             to pull request (excluded)
-# -s STEP           every n pull requests
+# -s STEP           every n pull requests, defaults to 0
+# -o FILE           data output to FILE, defaults to history.csv
 #
 # Change test plans in `bin/plan`.
 #
@@ -41,54 +42,99 @@ cd $PROG_HOME
 
 source bin/config
 args="$@"
-plans=$(cat bin/plan | grep "^[^#]")
-log_file="$PROG_HOME/logs/$(date +%m-%d-%H.%M)-regression.out"
 
 ## errors
 
 function report {
-  content=$(tail -n 20 $log_file)
-  message="regression failed for following benchmarks:
+  message="regression scheduling failed for following benchmarks:
 
 arguments: $args
-
-$plans
-
-Error message:
-
-$content
-
-
-[check $log_file for more information]"
+"
 
   ghi comment $MONITOR_ISSUE -m "$message" -- $MONITOR_REPO
 }
 
 trap report ERR
 
-## work
+# parse command line params
+while getopts "f:t:s:o:" opt; do
+ case $opt in
+    f)
+      FROM_PR=$OPTARG
+      ;;
+    t)
+      TILL_PR=$OPTARG
+      ;;
+    s)
+      SKIP=$OPTARG
+      ;;
+    o)
+      FILE=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
 
-bin/schedule $args -o "$PROG_HOME/regression.csv" >> $log_file 2>&1
 
-cat regression.csv | cat - history.csv > temp.csv && mv temp.csv history.csv
+shift $((OPTIND-1))
 
-bin/deploy >> $log_file 2>&1
 
-git add history.csv
-git commit -m "[bot]add data to history" >> $log_file 2>&1
-git push origin master:master >> $log_file 2>&1
+if [[ -z $FILE ]]; then
+  FILE="$PROG_HOME/history.csv"
+  echo "output file defaults to history.csv"
+fi
 
-## success message
+if [[ -z $SKIP ]]; then
+  SKIP=0
+  echo "skip steps defaults to $SKIP"
+fi
 
-message="regression finished successfully:
+# schedule
 
-arguments: $args
+cd "$PROG_HOME/dotty"
+git fetch origin master
 
-$plans
+# c488e01 is the commit that refactors the repo
+merge_commits=$(git log --merges --pretty=format:'%h,%an,%ad,%s' c488e01..HEAD --reverse)
 
-Visit $WEB_URL to see the changes."
+skip_counter=$SKIP
+in_range=false
 
-ghi comment $MONITOR_ISSUE -m "$message" -- $MONITOR_REPO
+while IFS= read -r commit_line
+do
+  commit=$(echo $commit_line | cut -d',' -f1)
+  author=$(echo $commit_line | cut -d',' -f2)
+  time=$(echo $commit_line | cut -d',' -f3)
 
-# restore plan
-rm regression.csv
+  if [[ $commit_line == *"Merge pull request #"* ]]; then
+    pr=$(echo $commit_line | cut -d',' -f4 | grep -o 'pull request #[0-9]\+' | grep -o '[0-9]\+')
+
+    # finish test when TILL_PR is reached
+    if [[ $pr == $TILL_PR ]]; then
+       exit 0
+    fi
+
+    if [[ $in_range == "true" ]]; then
+
+        if ((skip_counter == SKIP)); then
+          echo "bin/gauge $pr $commit -o \"$FILE\"" > "$PROG_HOME/jobs/work-regression-$pr.job"
+          skip_counter=0
+        else
+          skip_counter=$(expr $skip_counter + 1)
+        fi
+    fi
+
+    if [[ $pr == $FROM_PR ]]; then
+       in_range=true
+    fi
+
+  fi
+done <<< "$merge_commits"
+
